In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("dataset/world_cup_matches.csv")
df

,ID,Year,Date,Stage,Home Team,Home Goals,Away Goals,Away Team,Win Conditions,Host Team
0,1,1930,1930-07-13,Group stage,France,4,1,Mexico,NaN,False
1,2,1930,1930-07-13,Group stage,United States,3,0,Belgium,NaN,False
2,3,1930,1930-07-14,Group stage,Yugoslavia,2,1,Brazil,NaN,False
3,4,1930,1930-07-14,Group stage,Romania,3,1,Peru,NaN,False
4,5,1930,1930-07-15,Group stage,Argentina,1,0,France,NaN,False
...,...,...,...,...,...,...,...,...,...,...
895,896,2018,2018-07-07,Quarter-finals,Russia,2,2,Croatia,Croatia win on penalties (3 - 4),True
896,897,2018,2018-07-10,Semi-finals,France,1,0,Belgium,NaN,False
897,898,2018,2018-07-11,Semi-finals,Croatia,2,1,England,Extra time,False
898,899,2018,2018-07-14,Third place,Belgium,2,0,England,NaN,False
899,900,2018,2018-07-15,Final,France,4,2,Croatia,NaN,False

In [16]:
iran = df[(df['Home Team'] == 'Iran') | (df['Away Team'] == 'Iran')]
iran.shape

(15, 10)

In [17]:
all_teams_unique = pd.concat([df['Away Team'], df['Home Team']]).value_counts(dropna=0)
all_teams_unique.sample(20)

Greece            10
Panama             3
Hungary           32
El Salvador        6
South Korea       34
Algeria           13
England           69
Russia            45
Iceland            3
France            66
Cuba               3
Iraq               3
Poland            34
Japan             21
Paraguay          27
Belgium           48
Czechoslovakia    30
Uruguay           56
Turkey            10
United States     33
Name: count, dtype: int64

In [18]:
def find_winner(row):
    if row['Home Goals'] > row['Away Goals']:
        return row['Home Team']
    elif row['Away Goals'] > row['Home Goals']:
        return row['Away Team']
    else:
        return 'Draw'

In [19]:
df['winner']= df.apply(find_winner, axis=1)
df

,ID,Year,Date,Stage,Home Team,Home Goals,Away Goals,Away Team,Win Conditions,Host Team,winner
0,1,1930,1930-07-13,Group stage,France,4,1,Mexico,NaN,False,France
1,2,1930,1930-07-13,Group stage,United States,3,0,Belgium,NaN,False,United States
2,3,1930,1930-07-14,Group stage,Yugoslavia,2,1,Brazil,NaN,False,Yugoslavia
3,4,1930,1930-07-14,Group stage,Romania,3,1,Peru,NaN,False,Romania
4,5,1930,1930-07-15,Group stage,Argentina,1,0,France,NaN,False,Argentina
...,...,...,...,...,...,...,...,...,...,...,...
895,896,2018,2018-07-07,Quarter-finals,Russia,2,2,Croatia,Croatia win on penalties (3 - 4),True,Draw
896,897,2018,2018-07-10,Semi-finals,France,1,0,Belgium,NaN,False,France
897,898,2018,2018-07-11,Semi-finals,Croatia,2,1,England,Extra time,False,Croatia
898,899,2018,2018-07-14,Third place,Belgium,2,0,England,NaN,False,Belgium
899,900,2018,2018-07-15,Final,France,4,2,Croatia,NaN,False,France

In [20]:
df['winner'].value_counts().tail(22)

winner
Algeria                   3
Ivory Coast               3
Bulgaria                  3
Iran                      2
Republic of Ireland       2
East Germany              2
Serbia                    2
Greece                    2
Ukraine                   2
Morocco                   2
Tunisia                   2
Norway                    2
Australia                 2
South Africa              2
Wales                     1
North Korea               1
Cuba                      1
Jamaica                   1
Czech Republic            1
Slovenia                  1
Slovakia                  1
Bosnia and Herzegovina    1
Name: count, dtype: int64

In [21]:
df['winner'].count()

np.int64(900)

In [22]:
df.Stage.value_counts(dropna=1)

Stage
Group stage           528
Round of 16            89
First group stage      84
Quarter-finals         66
Semi-finals            36
Second group stage     36
Final                  20
Third place            19
First round            16
Final round             6
Name: count, dtype: int64

In [23]:
final_teams = df[df['Stage'] == 'Final']

In [ ]:
final_team = pd.concat([final_teams['Away Team'], final_teams['Home Team']]).value_counts(dropna=0)

In [25]:
df['final winner'] = final_teams.apply(find_winner, axis=1)

In [26]:
df['final winner'].value_counts()

final winner
Germany      4
Brazil       4
Italy        3
France       2
Argentina    2
Draw         2
Uruguay      1
England      1
Spain        1
Name: count, dtype: int64

In [27]:
final_team

Germany           8
Brazil            6
Italy             6
Argentina         5
Netherlands       3
France            3
Hungary           2
Czechoslovakia    2
Spain             1
Croatia           1
Uruguay           1
Sweden            1
England           1
Name: count, dtype: int64

In [28]:
df.isnull().sum()

ID                  0
Year                0
Date                0
Stage               0
Home Team           0
Home Goals          0
Away Goals          0
Away Team           0
Win Conditions    838
Host Team           0
winner              0
final winner      880
dtype: int64

In [29]:
df['Win Conditions'].unique()

array([nan, 'Extra time', 'Germany win on penalties (5 - 4)',
       'France win on penalties (3 - 4)',
       'Germany win on penalties (4 - 1)',
       'Belgium win on penalties (4 - 5)',
       'Republic of Ireland win on penalties (5 - 4)',
       'Argentina win on penalties (2 - 3)',
       'Argentina win on penalties (3 - 4)',
       'Germany win on penalties (4 - 3)',
       'Bulgaria win on penalties (1 - 3)',
       'Sweden win on penalties (4 - 5)',
       'Brazil win on penalties (3 - 2)',
       'Argentina win on penalties (4 - 3)',
       'Brazil win on penalties (4 - 2)', 'Golden goal',
       'Spain win on penalties (3 - 2)',
       'South Korea win on penalties (3 - 5)',
       'Ukraine win on penalties (0 - 3)',
       'Germany win on penalties (4 - 2)',
       'Portugal win on penalties (1 - 3)',
       'Italy win on penalties (5 - 3)',
       'Paraguay win on penalties (5 - 3)',
       'Uruguay win on penalties (4 - 2)',
       'Costa Rica win on penalties (5 - 3)',
       'Netherlands win on penalties (4 - 3)',
       'Argentina win on penalties (2 - 4)',
       'Russia win on penalties (4 - 3)',
       'Croatia win on penalties (3 - 2)',
       'England win on penalties (3 - 4)',
       'Croatia win on penalties (3 - 4)'], dtype=object)

In [30]:
df2022 = pd.DataFrame()

In [31]:
all_team = []

In [32]:
all_teams_unique.info()

<class 'pandas.core.series.Series'>
Index: 81 entries, Brazil to Indonesia
Series name: count
Non-Null Count  Dtype
--------------  -----
81 non-null     int64
dtypes: int64(1)
memory usage: 1.3+ KB

In [35]:
teams = pd.concat([df['Away Team'], df['Home Team']]).unique().tolist()

In [36]:
teams

['Mexico',
 'Belgium',
 'Brazil',
 'Peru',
 'France',
 'Bolivia',
 'Paraguay',
 'Romania',
 'Chile',
 'United States',
 'Yugoslavia',
 'Argentina',
 'Egypt',
 'Netherlands',
 'Switzerland',
 'Sweden',
 'Spain',
 'Hungary',
 'Austria',
 'Germany',
 'Czechoslovakia',
 'Indonesia',
 'Norway',
 'Poland',
 'Cuba',
 'Italy',
 'England',
 'Scotland',
 'Turkey',
 'South Korea',
 'Uruguay',
 'Wales',
 'Northern Ireland',
 'Russia',
 'Colombia',
 'Bulgaria',
 'North Korea',
 'Portugal',
 'Israel',
 'Morocco',
 'El Salvador',
 'Australia',
 'Haiti',
 'East Germany',
 'DR Congo',
 'Iran',
 'Tunisia',
 'Cameroon',
 'New Zealand',
 'Algeria',
 'Honduras',
 'Kuwait',
 'Iraq',
 'Denmark',
 'Canada',
 'Republic of Ireland',
 'United Arab Emirates',
 'Costa Rica',
 'Saudi Arabia',
 'Greece',
 'Nigeria',
 'South Africa',
 'Japan',
 'Croatia',
 'Jamaica',
 'Senegal',
 'Slovenia',
 'Ecuador',
 'China',
 'Ivory Coast',
 'Czech Republic',
 'Ghana',
 'Togo',
 'Ukraine',
 'Trinidad and Tobago',
 'Serbia',
 'Angola',
 'Slovakia',
 'Bosnia and Herzegovina',
 'Iceland',
 'Panama']

In [44]:
asia = ['Austria', 'Indonesia']
europe = ['Belgium', 'France', 'Romania', 'Yugoslavia', 'Netherlands', 'Switzerland', 'Sweden', 'Spain', 'Hungary', 'Germany', 'Czechoslovakia',
          'Norway', 'Poland', 'Italy', 'England', 'Scotland']
north_america = ['Mexico', 'United States', 'Cuba']
south_america = ['Brazil', 'Peru', 'Bolivia', 'Paraguay', 'Chile', 'Argentina']
africa = ['Egypt', ]
oceania = []

#last Scotland